BORDER_OFFSET = 1
TIC_TIMEOUT = 0.1
STAR_SYMBOLS = '+*.:'

SPACE_KEY_CODE = 32
LEFT_KEY_CODE = 260
RIGHT_KEY_CODE = 261
UP_KEY_CODE = 259
DOWN_KEY_CODE = 258

YEAR_BLOCK_WIDTH = 40
YEAR_BLOCK_HEIGHT = 6

GUN_AVAILABLE_YEAR = 2020

GARBAGE_DIR = 'animations/garbage'
